# Generated by Django 5.1.5 on 2025-01-28 19:03

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCardSet',
            fields=[
                ('uid', models.CharField(default=api.models.generate_unique_uid, editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('content', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='MileStone',
            fields=[
                ('uid', models.CharField(default=api.models.generate_unique_uid, editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('topics', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('uid', models.CharField(default=api.models.generate_unique_uid, editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('uid', models.CharField(default=api.models.generate_unique_uid, editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('event_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('uid', models.CharField(default=api.models.generate_unique_uid, editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('heading', models.CharField(max_length=150)),
                ('points', models.JSONField(default=dict)),
                ('image', models.ImageField(upload_to='flashcards')),
                ('set_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='api.flashcardset')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('uid', models.CharField(default=api.models.generate_unique_uid, editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('label_name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('uid', models.CharField(default=api.models.generate_unique_uid, editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('url', models.FileField(upload_to='pdfs')),
                ('size', models.IntegerField()),
                ('notes', models.JSONField(default=dict)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PDFChats',
            fields=[
                ('uid', models.CharField(default=api.models.generate_unique_uid, editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('sender', models.BooleanField()),
                ('content', models.CharField(max_length=1000)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='api.pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uid', models.CharField(default=api.models.generate_unique_uid, editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('difficulty', models.CharField(max_length=150)),
                ('parent_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('uid', models.CharField(default=api.models.generate_unique_uid, editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('estimated_time', models.CharField(max_length=50)),
                ('parent_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('uid', models.CharField(default=api.models.generate_unique_uid, editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=150)),
                ('current_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_roadmaps', to='api.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pdf',
            name='parent_roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='api.roadmap'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='parent_roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='api.roadmap'),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='parent_roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to='api.roadmap'),
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('uid', models.CharField(default=api.models.generate_unique_uid, editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('label', models.CharField(choices=[('PRIORITY', 'Priority'), ('WORK', 'Work'), ('EXAM', 'Exam'), ('PERSONAL', 'Personal')], default='PERSONAL', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
