# Generated by Django 5.0.4 on 2024-10-30 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_label_calendar_pdf_pdfchats_roadmap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.roadmapstate'),
        ),
    ]
