# Generated by Django 5.1.5 on 2025-01-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
