# Generated by Django 5.0.4 on 2024-10-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_roadmap_current_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='color',
            field=models.CharField(max_length=10),
        ),
    ]
