# Generated by Django 5.1.5 on 2025-01-31 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_roadmap_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='cid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
