# Generated by Django 5.0.4 on 2024-10-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_calendar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfchats',
            name='date_uploded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
