# Generated by Django 5.1.5 on 2025-02-07 13:56

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pdf_cid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uid', models.CharField(default=api.models.generate_unique_uid, editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('eventTitle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('colorHex', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
