# Generated by Django 5.0.4 on 2024-10-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pdfchats_date_uploded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='CID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
