# Generated by Django 4.2.4 on 2025-12-30 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('correct_answer', models.CharField(max_length=100)),
                ('options', models.JSONField()),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.milestone')),
            ],
        ),
    ]
