# Generated by Django 5.0.4 on 2024-11-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pdf_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='uid',
            field=models.CharField(blank=True, default='t5g09Sf', editable=False, max_length=7, null=True, unique=True),
        ),
    ]
