# Generated by Django 5.0.4 on 2024-11-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pdf_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='uid',
            field=models.CharField(blank=True, default='i3JkJlz', editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='uid',
            field=models.CharField(blank=True, default='N9lhF1l', editable=False, max_length=7, null=True, unique=True),
        ),
    ]
