# Generated by Django 5.0.4 on 2024-11-24 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_roadmap_uid_alter_pdf_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='uid',
            field=models.CharField(blank=True, default='DfYrIuj', editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='uid',
            field=models.CharField(blank=True, default='esBv3ZQ', editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FlashCardSet',
            fields=[
                ('uid', models.CharField(default='0T0yWAq', editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('content', models.JSONField()),
                ('parent_roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roadmap')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('points', models.JSONField()),
                ('image', models.ImageField(upload_to='flashcards')),
                ('set_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flashcardset')),
            ],
        ),
    ]
