# Generated by Django 5.0.4 on 2024-11-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_pdf_uid_alter_roadmap_uid_flashcardset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='CID',
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='uid',
            field=models.CharField(default='bkAbhwv', editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='uid',
            field=models.CharField(blank=True, default='F801cru', editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='uid',
            field=models.CharField(blank=True, default='oghTyBg', editable=False, max_length=7, null=True, unique=True),
        ),
    ]
