# Generated by Django 5.0.4 on 2024-11-25 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_pdf_cid_alter_flashcardset_uid_alter_pdf_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('difficulty', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('estimated_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='roadmapstate',
            name='parent_roadmap',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='current_state',
        ),
        migrations.RenameField(
            model_name='roadmap',
            old_name='description',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='roadmap',
            old_name='name',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='uid',
            field=models.CharField(default='i2ui0So', editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='uid',
            field=models.CharField(blank=True, default='lzTgpVh', editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='uid',
            field=models.CharField(blank=True, default='Gf62H8U', editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MileStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('topics', models.JSONField()),
                ('parent_roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roadmap')),
            ],
        ),
        migrations.AddField(
            model_name='roadmap',
            name='current_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.milestone'),
        ),
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.DeleteModel(
            name='RoadmapState',
        ),
    ]
