# Generated by Django 5.0.4 on 2024-11-25 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_flashcardset_uid_alter_pdf_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.milestone'),
        ),
        migrations.AddField(
            model_name='resource',
            name='parent_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.milestone'),
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='uid',
            field=models.CharField(default='JnAkTHO', editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='uid',
            field=models.CharField(blank=True, default='Ryc9gj1', editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='uid',
            field=models.CharField(blank=True, default='WmfPnoo', editable=False, max_length=7, null=True, unique=True),
        ),
    ]
