# Generated by Django 5.0.4 on 2024-11-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_project_parent_milestone_resource_parent_milestone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardset',
            name='uid',
            field=models.CharField(default='NLTqRo9', editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='uid',
            field=models.CharField(blank=True, default='BEXSkFi', editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='uid',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
    ]
