# Generated by Django 5.1.5 on 2025-01-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_flashcardset_uid_alter_pdf_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='id',
        ),
        migrations.AddField(
            model_name='todo',
            name='uid',
            field=models.CharField(default='XrB6HOg', editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='uid',
            field=models.CharField(default='y1MI1eF', editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='uid',
            field=models.CharField(blank=True, default='dAOCIkd', editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='label',
            field=models.CharField(choices=[('PRIORITY', 'Priority'), ('WORK', 'Work'), ('EXAM', 'Exam'), ('PERSONAL', 'Personal')], default='PERSONAL', max_length=20),
        ),
    ]
