# Generated by Django 5.1.5 on 2025-01-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_todo_id_todo_uid_alter_flashcardset_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='uid',
            field=models.CharField(default='fHWYqtn', editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='uid',
            field=models.CharField(blank=True, default='m6YCqNn', editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.CharField(default='240GAzH', editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
