# Generated by Django 5.1.5 on 2025-01-28 10:45

import django.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_todo_title_alter_flashcardset_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardset',
            name='uid',
            field=models.CharField(default='dcov858', editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='uid',
            field=models.CharField(blank=True, default='WajHgf7', editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
