# Generated by Django 5.1.5 on 2025-01-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_flashcardset_uid_alter_pdf_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardset',
            name='uid',
            field=models.CharField(default='AgvjPqk', editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='uid',
            field=models.CharField(blank=True, default='BP68seX', editable=False, max_length=7, null=True, unique=True),
        ),
    ]
