# Generated by Django 5.1.5 on 2025-01-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_flashcardset_uid_alter_pdf_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardset',
            name='uid',
            field=models.CharField(default='tFB8zL9', editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='uid',
            field=models.CharField(blank=True, default='CMzFkc9', editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.CharField(default='SsDTZkp', editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
