# Generated by Django 5.1.5 on 2025-01-28 11:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_flashcardset_uid_alter_pdf_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardset',
            name='uid',
            field=models.CharField(default='QbrKM6r', editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='uid',
            field=models.CharField(blank=True, default='vLBvYUb', editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.CharField(default=api.models.generate_unique_uid, editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
